version: '3'
services:
  db:
    container_name: database
    image: postgres:16
    hostname: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    ports:
      - "5432:5432"
